//! Golden tests: REAL flamo / torchfx.ddsp checkpoints (generated by the libraries
//! themselves — see `tests/fixtures/checkpoints/`) import to the exact coefficients
//! the source library computes. `golden.json` holds per-fixture `[b0,b1,b2,a0,a1,a2]`
//! recovered from flamo's own `get_poly_coeff` spectra / torchfx's `sos()`.
#![cfg(feature = "checkpoint")]

use std::path::PathBuf;

use fluxion_io::checkpoint::{FlamoBiquadType, ImportOptions, Kind, SvfType, import_safetensors};

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/checkpoints")
}

/// Minimal golden.json access without a JSON dependency: the file is generated with
/// `indent=1`, so `"sections_ba"` arrays can be scraped per fixture name. To keep this
/// robust we parse with serde_json — available transitively via fluxion-core's envelope
/// (a dev-dependency here).
fn load_golden() -> serde_json::Value {
    let s = std::fs::read_to_string(fixtures().join("golden.json")).unwrap();
    serde_json::from_str(&s).unwrap()
}

fn opts_from_golden(o: &serde_json::Value) -> ImportOptions {
    let mut opts = ImportOptions::default();
    if let Some(fs) = o["fs"].as_u64() {
        opts.fs = Some(fs as u32);
    }
    if let Some(k) = o["kind"].as_str() {
        opts.kind = Kind::from_name(k).unwrap();
    }
    if let Some(t) = o["svf_type"].as_str() {
        opts.svf_type = SvfType::from_name(t).unwrap();
    }
    if let Some(t) = o["biquad_type"].as_str() {
        opts.biquad_type = FlamoBiquadType::from_name(t).unwrap();
    }
    if let Some(v) = o["eq_f_lo"].as_f64() {
        opts.eq.f_lo = v;
    }
    if let Some(v) = o["eq_f_hi"].as_f64() {
        opts.eq.f_hi = v;
    }
    if let Some(v) = o["eq_max_gain_db"].as_f64() {
        opts.eq.max_gain_db = v;
    }
    opts
}

#[test]
fn every_fixture_matches_its_library_computed_golden() {
    let golden = load_golden();
    let map = golden.as_object().unwrap();
    assert!(map.len() >= 15, "fixture set shrank: {}", map.len());

    for (name, entry) in map {
        let opts = opts_from_golden(&entry["opts"]);
        let path = fixtures().join(format!("{name}.safetensors"));
        let imported = import_safetensors(&path, &opts)
            .unwrap_or_else(|e| panic!("{name}: import failed: {e}"));

        let want: Vec<Vec<f64>> = entry["sections_ba"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| {
                row.as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_f64().unwrap())
                    .collect()
            })
            .collect();

        assert_eq!(imported.sections.len(), want.len(), "{name}: section count");
        for (i, (got, w)) in imported.sections.iter().zip(&want).enumerate() {
            // Golden rows are [b0,b1,b2,a0,a1,a2] straight from the library (f32
            // forward); normalise by a0 and compare against the imported
            // [b0,b1,b2,a1,a2]. The library computed in f32, we replay in f64 —
            // agreement is bounded by the source's f32 rounding.
            let a0 = w[3];
            let wn = [w[0] / a0, w[1] / a0, w[2] / a0, w[4] / a0, w[5] / a0];
            for (j, (g, e)) in got.iter().zip(&wn).enumerate() {
                let diff = (f64::from(*g) - e).abs();
                assert!(
                    diff < 5e-5,
                    "{name}: section {i} coeff {j}: got {g}, want {e} (diff {diff:.2e})"
                );
            }
        }
    }
}
