//! wasm renders what native renders (roadmap W2).
//!
//! The claim the whole browser story rests on is "preview and export come from the same DSP". This
//! is where that stops being a slogan: a fixture holds an input signal and the output native
//! produces for it, and `js/parity.mjs` feeds the same input through the built wasm module and
//! compares. Nothing here is wasm-specific, so it runs in `cargo test --workspace`; the Node side
//! then needs no Rust toolchain, which is what lets the `wasm` CI job be a plain `node` invocation.
//!
//! Regenerate the fixture only when the reference output legitimately changes:
//!
//! ```text
//! cargo test -p fluxion-wasm --test parity -- --ignored write_fixture
//! ```

use fluxion::{Graph, Signal, process};

/// The chain from the roadmap's own W2 check.
const CHAIN: &str = "highpass(80, 4) | gain(-3dB)";
const FS: u32 = 48_000;
const FRAMES: usize = 1024;

/// The tolerance W2 asks for. Both sides run the identical Rust code, so the only difference is
/// wasm's f32 arithmetic; anything approaching this bound would mean a real divergence.
const TOLERANCE: f32 = 1e-6;

/// A deterministic input with content across the band: a 220 Hz sine, a 6 kHz sine, and a DC
/// offset plus low rumble for the high-pass to actually remove.
fn input() -> Vec<f32> {
    (0..FRAMES)
        .map(|n| {
            let t = n as f32 / FS as f32;
            let tau = std::f32::consts::TAU;
            0.4 * (tau * 220.0 * t).sin()
                + 0.2 * (tau * 6000.0 * t).sin()
                + 0.1 * (tau * 20.0 * t).sin()
        })
        .collect()
}

fn native() -> Vec<f32> {
    let graph: Graph = CHAIN.parse().expect("the fixture chain parses");
    let out = process(&graph, &Signal::new(FS, vec![input()]));
    out.channels.into_iter().next().unwrap()
}

/// The committed fixture, as `{"chain", "fs", "input": [...], "expected": [...]}`.
fn fixture() -> serde_json::Value {
    serde_json::from_str(include_str!("../js/fixtures/parity.json")).expect("the fixture is JSON")
}

fn floats(value: &serde_json::Value, key: &str) -> Vec<f32> {
    value[key]
        .as_array()
        .unwrap_or_else(|| panic!("fixture has no array '{key}'"))
        .iter()
        .map(|v| v.as_f64().expect("a number") as f32)
        .collect()
}

/// Pre-condition: the committed fixture was written from this chain on this input.
/// Post-condition: native still produces it. If this goes red the DSP changed, and the Node-side
/// comparison would be measuring against a stale reference rather than against native.
#[test]
fn the_fixture_still_matches_native() {
    let fixture = fixture();
    assert_eq!(fixture["chain"], CHAIN);
    assert_eq!(fixture["fs"], FS);
    assert_eq!(
        floats(&fixture, "input"),
        input(),
        "the fixture input drifted"
    );

    let expected = floats(&fixture, "expected");
    let actual = native();
    assert_eq!(expected.len(), actual.len());
    for (n, (a, b)) in expected.iter().zip(&actual).enumerate() {
        assert!(
            (a - b).abs() <= TOLERANCE,
            "sample {n}: fixture {a}, native {b} (tolerance {TOLERANCE})"
        );
    }
}

/// The chain text survives the trip through the module's own accessor, which is what `parity.mjs`
/// checks on the wasm side.
#[test]
fn the_chain_text_is_canonical() {
    let graph: Graph = CHAIN.parse().unwrap();
    let rendered = graph.to_string();
    assert_eq!(rendered.parse::<Graph>().unwrap(), graph);
    assert_eq!(rendered, "highpass(80, 4) | gain(0.70794576)");
}

/// See the module docs. Writes `js/fixtures/parity.json`.
#[test]
#[ignore = "writes the committed fixture; run explicitly"]
fn write_fixture() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("js/fixtures/parity.json");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    let json = serde_json::json!({
        "_comment": "Generated by `cargo test -p fluxion-wasm --test parity -- --ignored \
                     write_fixture`. Native reference output for the wasm parity check.",
        "chain": CHAIN,
        "fs": FS,
        "tolerance": TOLERANCE,
        "input": input(),
        "expected": native(),
    });
    std::fs::write(&path, serde_json::to_string_pretty(&json).unwrap()).unwrap();
    eprintln!("wrote {} frames to {}", FRAMES, path.display());
}
