// Generated by scripts/gen_interfaces.py from the op registry — do not edit.
//
// The catalog as plain data: op names, groups, parameters, defaults and ranges, identical to what
// the Rust library, the CLI, Python and C see. The wasm module deliberately does not carry this
// (it would grow the download for something most pages never read at run time), so it lives here
// where a bundler can drop it if unused.

/** Every op fluxion knows, as a literal union — a typo is a compile error. */
export type OpName =
  | "gain"
  | "lowpass"
  | "highpass"
  | "normalize"
  | "peaking"
  | "lowshelf"
  | "highshelf"
  | "notch"
  | "bandpass"
  | "allpass"
  | "delay"
  | "echo"
  | "cheby1_lowpass"
  | "cheby1_highpass"
  | "cheby2_lowpass"
  | "cheby2_highpass"
  | "reverb"
  | "fir"
  | "fade"
  | "tremolo"
  | "overdrive"
  | "compand"
  | "reverse"
  | "biquad"
  | "chorus"
  | "flanger"
  | "limiter"
  | "loudnorm"
  | "phaser"
  | "pitchshift"
  | "gate";

/** Which section of the catalog an op belongs to. */
export type OpGroup = "filter" | "effect";

/** What a parameter is measured in. */
export type Unit = "hz" | "db" | "seconds" | "q" | "linear";

/** One parameter of an op. `min` / `max` are `null` when unbounded. */
export interface OpParam {
  readonly name: string;
  readonly unit: Unit;
  readonly default: number;
  readonly min: number | null;
  readonly max: number | null;
}

/** One op: what it is called, what it does, and what it takes. */
export interface OpSpec {
  readonly name: OpName;
  readonly group: OpGroup;
  /** True when the parameters are a variable-length list rather than a fixed tuple (`fir`). */
  readonly variadic: boolean;
  readonly doc: string;
  readonly params: readonly OpParam[];
}

export declare const OPS: Readonly<Record<OpName, OpSpec>>;
export declare const OP_NAMES: readonly OpName[];
