// Generated by scripts/gen_interfaces.py from the op registry — do not edit.
//
// The catalog as plain data: op names, groups, parameters, defaults and ranges, identical to what
// the Rust library, the CLI, Python and C see. The wasm module deliberately does not carry this
// (it would grow the download for something most pages never read at run time), so it lives here
// where a bundler can drop it if unused.


/** @type {Readonly<Record<string, import('./ops.js').OpSpec>>} */
export const OPS = Object.freeze({
  "gain": {
    name: "gain",
    group: "effect",
    variadic: false,
    doc: "Linear gain, `y = x * gain`.",
    params: [{ name: "gain", unit: "linear", default: 1.0, min: null, max: null }],
  },
  "lowpass": {
    name: "lowpass",
    group: "filter",
    variadic: false,
    doc: "Butterworth low-pass filter (`cutoff` Hz, integer `order`). The `lowpass` node.",
    params: [{ name: "cutoff", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "order", unit: "linear", default: 2.0, min: 1.0, max: 16.0 }],
  },
  "highpass": {
    name: "highpass",
    group: "filter",
    variadic: false,
    doc: "Butterworth high-pass filter (`cutoff` Hz, integer `order`). The `highpass` node.",
    params: [{ name: "cutoff", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "order", unit: "linear", default: 2.0, min: 1.0, max: 16.0 }],
  },
  "normalize": {
    name: "normalize",
    group: "effect",
    variadic: false,
    doc: "Peak normalization to a target linear `peak`.",
    params: [{ name: "peak", unit: "linear", default: 1.0, min: 0.0, max: null }],
  },
  "peaking": {
    name: "peaking",
    group: "filter",
    variadic: false,
    doc: "RBJ peaking EQ: `gain` dB around `frequency` with bandwidth `q`.",
    params: [{ name: "frequency", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "gain", unit: "db", default: 0.0, min: null, max: null }, { name: "q", unit: "q", default: 0.707, min: 0.001, max: 1000.0 }],
  },
  "lowshelf": {
    name: "lowshelf",
    group: "filter",
    variadic: false,
    doc: "RBJ low shelf: `gain` dB below `frequency` (bandwidth `q`).",
    params: [{ name: "frequency", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "gain", unit: "db", default: 0.0, min: null, max: null }, { name: "q", unit: "q", default: 0.707, min: 0.001, max: 1000.0 }],
  },
  "highshelf": {
    name: "highshelf",
    group: "filter",
    variadic: false,
    doc: "RBJ high shelf: `gain` dB above `frequency` (bandwidth `q`).",
    params: [{ name: "frequency", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "gain", unit: "db", default: 0.0, min: null, max: null }, { name: "q", unit: "q", default: 0.707, min: 0.001, max: 1000.0 }],
  },
  "notch": {
    name: "notch",
    group: "filter",
    variadic: false,
    doc: "RBJ notch at `frequency` with bandwidth `q`.",
    params: [{ name: "frequency", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "q", unit: "q", default: 0.707, min: 0.001, max: 1000.0 }],
  },
  "bandpass": {
    name: "bandpass",
    group: "filter",
    variadic: false,
    doc: "RBJ band-pass (0 dB peak) at `frequency` with bandwidth `q`.",
    params: [{ name: "frequency", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "q", unit: "q", default: 0.707, min: 0.001, max: 1000.0 }],
  },
  "allpass": {
    name: "allpass",
    group: "filter",
    variadic: false,
    doc: "RBJ all-pass at `frequency` with bandwidth `q`.",
    params: [{ name: "frequency", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "q", unit: "q", default: 0.707, min: 0.001, max: 1000.0 }],
  },
  "delay": {
    name: "delay",
    group: "effect",
    variadic: false,
    doc: "Single delayed tap crossfaded with the dry signal (`time` s, `mix`).",
    params: [{ name: "time", unit: "seconds", default: 0.25, min: 0.0, max: 60.0 }, { name: "mix", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }],
  },
  "echo": {
    name: "echo",
    group: "effect",
    variadic: false,
    doc: "Feedback echo: `wet` repeating echoes spaced `time` s apart with `feedback`.",
    params: [{ name: "time", unit: "seconds", default: 0.25, min: 0.0, max: 60.0 }, { name: "feedback", unit: "linear", default: 0.3, min: 0.0, max: 0.99 }, { name: "wet", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }],
  },
  "cheby1_lowpass": {
    name: "cheby1_lowpass",
    group: "filter",
    variadic: false,
    doc: "Chebyshev Type I low-pass (`cutoff` Hz, `order`, passband `ripple` dB).",
    params: [{ name: "cutoff", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "order", unit: "linear", default: 4.0, min: 1.0, max: 16.0 }, { name: "ripple", unit: "db", default: 1.0, min: 0.01, max: 12.0 }],
  },
  "cheby1_highpass": {
    name: "cheby1_highpass",
    group: "filter",
    variadic: false,
    doc: "Chebyshev Type I high-pass (`cutoff` Hz, `order`, passband `ripple` dB).",
    params: [{ name: "cutoff", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "order", unit: "linear", default: 4.0, min: 1.0, max: 16.0 }, { name: "ripple", unit: "db", default: 1.0, min: 0.01, max: 12.0 }],
  },
  "cheby2_lowpass": {
    name: "cheby2_lowpass",
    group: "filter",
    variadic: false,
    doc: "Chebyshev Type II low-pass (`cutoff` = stopband edge Hz, `order`, stopband `atten` dB).",
    params: [{ name: "cutoff", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "order", unit: "linear", default: 4.0, min: 1.0, max: 16.0 }, { name: "atten", unit: "db", default: 40.0, min: 10.0, max: 120.0 }],
  },
  "cheby2_highpass": {
    name: "cheby2_highpass",
    group: "filter",
    variadic: false,
    doc: "Chebyshev Type II high-pass (`cutoff` = stopband edge Hz, `order`, stopband `atten` dB).",
    params: [{ name: "cutoff", unit: "hz", default: 1000.0, min: 0.0, max: null }, { name: "order", unit: "linear", default: 4.0, min: 1.0, max: 16.0 }, { name: "atten", unit: "db", default: 40.0, min: 10.0, max: 120.0 }],
  },
  "reverb": {
    name: "reverb",
    group: "effect",
    variadic: false,
    doc: "Schroeder\u2013Moorer reverb (`room` size, `damping`, wet/dry `mix`).",
    params: [{ name: "room", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }, { name: "damping", unit: "linear", default: 0.3, min: 0.0, max: 1.0 }, { name: "mix", unit: "linear", default: 0.3, min: 0.0, max: 1.0 }],
  },
  "fir": {
    name: "fir",
    group: "filter",
    variadic: true,
    doc: "Direct-form FIR filter: `y[n] = \u03a3_k taps[k]\u00b7x[n-k]`. Variadic \u2014 its parameters are the tap vector itself (one or more), the realtime/graph form of a trained or frozen FIR. The one parameter listed is the prototype for a single tap.",
    params: [{ name: "tap", unit: "linear", default: 1.0, min: null, max: null }],
  },
  "fade": {
    name: "fade",
    group: "effect",
    variadic: false,
    doc: "Amplitude fade: `fadein` seconds ramping in, `fadeout` seconds ramping out, with a `shape` curve (0 = linear, 1 = quarter-sine [the SoX default], 2 = half-sine). Length-preserving.",
    params: [{ name: "fadein", unit: "seconds", default: 0.0, min: 0.0, max: 3600.0 }, { name: "fadeout", unit: "seconds", default: 0.0, min: 0.0, max: 3600.0 }, { name: "shape", unit: "linear", default: 1.0, min: 0.0, max: 2.0 }],
  },
  "tremolo": {
    name: "tremolo",
    group: "effect",
    variadic: false,
    doc: "Tremolo: amplitude LFO at `rate` Hz dipping by `depth` (0..1). Length-preserving.",
    params: [{ name: "rate", unit: "hz", default: 5.0, min: 0.0, max: 20000.0 }, { name: "depth", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }],
  },
  "overdrive": {
    name: "overdrive",
    group: "effect",
    variadic: false,
    doc: "Overdrive: `gain` dB of drive through a `tanh` soft-clipper with a `colour` asymmetry bias. Nonlinear (not differentiable here).",
    params: [{ name: "gain", unit: "db", default: 20.0, min: 0.0, max: 100.0 }, { name: "colour", unit: "linear", default: 0.2, min: 0.0, max: 1.0 }],
  },
  "compand": {
    name: "compand",
    group: "effect",
    variadic: false,
    doc: "Feed-forward compressor / expander (compand): one-pole peak-envelope follower (`attack`, `release` s) driving a soft-knee gain computer (`threshold` dBFS, `ratio`, `knee` dB, `makeup` dB). Stateful per-channel \u2014 realtime-playable.",
    params: [{ name: "attack", unit: "seconds", default: 0.01, min: 0.0, max: 10.0 }, { name: "release", unit: "seconds", default: 0.1, min: 0.0, max: 10.0 }, { name: "threshold", unit: "db", default: -20.0, min: -120.0, max: 0.0 }, { name: "ratio", unit: "linear", default: 4.0, min: 1.0, max: 100.0 }, { name: "knee", unit: "db", default: 6.0, min: 0.0, max: 48.0 }, { name: "makeup", unit: "db", default: 0.0, min: -48.0, max: 48.0 }],
  },
  "reverse": {
    name: "reverse",
    group: "effect",
    variadic: false,
    doc: "Per-channel time reversal (no parameters). Length-preserving, but not realtime (it needs the whole signal).",
    params: [],
  },
  "biquad": {
    name: "biquad",
    group: "filter",
    variadic: false,
    doc: "A raw second-order section from explicit coefficients `b0 b1 b2 a1 a2` (`a0` normalized to 1). Reuses the biquad/SOS machinery, so it is differentiable / freezable / realtime like the designed filters.",
    params: [{ name: "b0", unit: "linear", default: 1.0, min: null, max: null }, { name: "b1", unit: "linear", default: 0.0, min: null, max: null }, { name: "b2", unit: "linear", default: 0.0, min: null, max: null }, { name: "a1", unit: "linear", default: 0.0, min: null, max: null }, { name: "a2", unit: "linear", default: 0.0, min: null, max: null }],
  },
  "chorus": {
    name: "chorus",
    group: "effect",
    variadic: false,
    doc: "Chorus: an LFO-modulated fractional-delay voice (`rate` Hz, `depth` s, `delay` s) blended by `mix`. Feed-forward (no feedback). Length-preserving.",
    params: [{ name: "rate", unit: "hz", default: 1.5, min: 0.0, max: 100.0 }, { name: "depth", unit: "seconds", default: 0.002, min: 0.0, max: 1.0 }, { name: "delay", unit: "seconds", default: 0.025, min: 0.0, max: 1.0 }, { name: "mix", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }],
  },
  "flanger": {
    name: "flanger",
    group: "effect",
    variadic: false,
    doc: "Flanger: a short LFO-modulated delay (`rate` Hz, `depth` s, `delay` s) with `feedback`, blended by `mix`. Length-preserving.",
    params: [{ name: "rate", unit: "hz", default: 0.5, min: 0.0, max: 100.0 }, { name: "depth", unit: "seconds", default: 0.002, min: 0.0, max: 1.0 }, { name: "delay", unit: "seconds", default: 0.001, min: 0.0, max: 1.0 }, { name: "feedback", unit: "linear", default: 0.5, min: -0.95, max: 0.95 }, { name: "mix", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }],
  },
  "phaser": {
    name: "phaser",
    group: "effect",
    variadic: false,
    doc: "Phaser: an LFO-swept cascade of first-order all-pass stages (`rate` Hz, `depth`) with `feedback`, blended by `mix`. Length-preserving.",
    params: [{ name: "rate", unit: "hz", default: 0.5, min: 0.0, max: 100.0 }, { name: "depth", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }, { name: "feedback", unit: "linear", default: 0.5, min: -0.95, max: 0.95 }, { name: "mix", unit: "linear", default: 0.5, min: 0.0, max: 1.0 }],
  },
});

/** Every op name, in catalog order. */
export const OP_NAMES = Object.freeze(Object.keys(OPS));
