// @generated by scripts/gen_loudness_golden.py — do not edit.
//
// Loudness oracle vectors: what pyloudnorm and ffmpeg's ebur128 independently measure for
// each signal. Baked in as consts so the Rust test needs neither of them installed.
// pyloudnorm 0.2.0, ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers

//! Loudness oracle vectors for `loudness_golden.rs`.
//!
//! pyloudnorm and ffmpeg's `ebur128` are the independent references for ITU-R BS.1770.
//! Signals are described by parameters and rebuilt identically by `signal()` in the test;
//! the case name is the join key.
#![allow(dead_code)]

/// One oracle case: how to rebuild the signal, and what the two references measured.
pub struct LoudnessCase {
    /// Case name; the join key with the test's own list.
    pub name: &'static str,
    /// Which shape `signal()` should build.
    pub kind: &'static str,
    /// Tone frequency, Hz (ignored by the noise cases).
    pub freq: f32,
    /// Peak amplitude, linear.
    pub amp: f32,
    /// Duration, seconds.
    pub seconds: f32,
    /// Channel count.
    pub channels: usize,
    /// Integrated loudness, LUFS, per pyloudnorm.
    pub pyloudnorm: f32,
    /// Integrated loudness, LUFS, per ffmpeg ebur128.
    pub ffmpeg: f32,
    /// Loudness range, LU, per ffmpeg.
    pub ffmpeg_lra: f32,
    /// True peak, dBTP, per ffmpeg.
    pub ffmpeg_true_peak: f32,
}

/// Every oracle case, in the order the generator emitted them.
#[rustfmt::skip]
pub const LOUDNESS_CASES: &[LoudnessCase] = &[
    LoudnessCase { name: "sine_1k_-20dbfs_rms", kind: "sine", freq: 1e+03f32, amp: 0.14142136f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -20.034708f32, ffmpeg: -2e+01f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -17.0f32 },
    LoudnessCase { name: "sine_1k_quiet", kind: "sine", freq: 1e+03f32, amp: 0.02f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -37.024406f32, ffmpeg: -37.0f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -34.0f32 },
    LoudnessCase { name: "sine_1k_loud", kind: "sine", freq: 1e+03f32, amp: 0.8f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -4.983208f32, ffmpeg: -5.0f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -1.9f32 },
    LoudnessCase { name: "sine_40hz", kind: "sine", freq: 4e+01f32, amp: 0.5f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -15.309085f32, ffmpeg: -15.3f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -6.0f32 },
    LoudnessCase { name: "sine_100hz", kind: "sine", freq: 1e+02f32, amp: 0.5f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -10.893638f32, ffmpeg: -10.9f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -6.0f32 },
    LoudnessCase { name: "sine_5khz", kind: "sine", freq: 5e+03f32, amp: 0.5f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -5.7515f32, ffmpeg: -5.7f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -6.0f32 },
    LoudnessCase { name: "sine_10khz", kind: "sine", freq: 1e+04f32, amp: 0.5f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -5.7231154f32, ffmpeg: -5.7f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -5.2f32 },
    LoudnessCase { name: "noise", kind: "noise", freq: 0.0f32, amp: 0.3f32, seconds: 1e+01f32, channels: 1, pyloudnorm: -12.123855f32, ffmpeg: -12.1f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -5.2f32 },
    LoudnessCase { name: "noise_stereo", kind: "noise", freq: 0.0f32, amp: 0.3f32, seconds: 1e+01f32, channels: 2, pyloudnorm: -11.154755f32, ffmpeg: -11.1f32, ffmpeg_lra: 0.0f32, ffmpeg_true_peak: -5.2f32 },
    LoudnessCase { name: "stepped", kind: "stepped", freq: 1e+03f32, amp: 0.5f32, seconds: 2e+01f32, channels: 1, pyloudnorm: -9.130577f32, ffmpeg: -9.1f32, ffmpeg_lra: 2e+01f32, ffmpeg_true_peak: -6.0f32 },
    LoudnessCase { name: "tone_then_silence", kind: "tone_then_silence", freq: 1e+03f32, amp: 0.5f32, seconds: 2e+01f32, channels: 1, pyloudnorm: -9.131238f32, ffmpeg: -9.1f32, ffmpeg_lra: 4.8f32, ffmpeg_true_peak: -6.0f32 },
];
