"""Type stubs for the compiled `fluxion._fluxion` extension."""

from numpy import float32
from numpy.typing import NDArray

F32 = NDArray[float32]

class Chain:
    """A lazy effect chain (a DSP graph). Compose with ``|``/``+``, apply with ``process``."""

    def process(self, x: F32, fs: int) -> F32:
        """Apply the chain at ``fs`` to a 1-D ``(T,)`` or 2-D ``(C, T)`` float32 array (same shape out)."""
        ...
    def process_batch(self, x: F32, fs: int) -> F32:
        """Filter a 2-D ``(B, T)`` batch of independent mono signals at ``fs`` → ``(B, T)`` float32.

        Identical to :meth:`process` per row, but routes a pure-filter chain through the batched
        SIMD kernel (rows vectorize across the batch). The CPU batch path; the GPU one is
        ``sos_filter_batch_gpu`` (CUDA wheel only).
        """
        ...
    def sos_coeffs(self, fs: int) -> F32:
        """Flat ``[b0,b1,b2,a1,a2]·n`` designed coefficients for a pure-filter chain at ``fs``."""
        ...
    def save_fxg(self, path: str) -> None:
        """Serialize the whole chain (biquads / FIR taps / gain / delay) to a ``.fxg`` artifact
        that a C/C++ host loads with ``fx_graph_load_fxg`` + ``fx_rt_new``. Sample-rate-agnostic."""
        ...
    def certify(self, fs: int) -> tuple[str, float]:
        """``(verdict, margin)`` on the stability ladder at ``fs`` — the certificate ``fx_rt_new``
        and ``RtChain.from_chain`` gate on."""
        ...
    def __or__(self, other: Chain) -> Chain: ...
    def __add__(self, other: Chain) -> Chain: ...
    def __repr__(self) -> str: ...

class RtChain:
    """A realtime, stateful executor for a :class:`Chain`: streams a signal block-by-block.

    Built once (lower + certify + pre-size), then :meth:`process` filters caller-provided
    float32 blocks in place, allocation-free, carrying filter state across calls and releasing
    the GIL while the Rust kernel runs. One ``RtChain`` is one mono stream — build one per
    channel for multichannel audio.
    """

    @staticmethod
    def from_chain(chain: Chain, fs: int, max_block: int = 4096) -> RtChain:
        """Lower ``chain`` at sample rate ``fs`` for blocks up to ``max_block`` samples.

        Certifies stability (an ``unstable`` chain raises ``ValueError``) and rejects chains
        containing an op with no realtime lowering (``normalize`` / ``fade`` / ``reverse`` /
        the modulated effects / feedback).
        """
        ...
    @staticmethod
    def from_sections(sections: F32, max_block: int = 4096) -> RtChain:
        """A realtime executor from already-designed ``(n_sections, 5)`` ``[b0,b1,b2,a1,a2]``
        coefficients (e.g. from ``import_state_dict``); ``fs`` is ``None``."""
        ...
    def process(self, input: F32, output: F32) -> None:
        """Filter one block: both 1-D float32 C-contiguous arrays, same length ≤ ``max_block``,
        distinct. State is carried across calls; the call is allocation-free."""
        ...
    def set_coeffs(self, node: int, sections: F32, fade_samples: int = 0) -> None:
        """Crossfade the ``node``-th filter (depth-first) to a new ``(n_sections, 5)`` cascade.
        Unstable sections raise ``ValueError``; an out-of-range node raises ``IndexError``.
        Control-plane call (converts + certifies, allocating): call it between blocks from a
        control thread, not from a hard-realtime audio callback."""
        ...
    def reset(self) -> None:
        """Reset all filter state and delay lines to silence (call on seek / source switch)."""
        ...
    @property
    def filter_count(self) -> int: ...
    @property
    def max_block(self) -> int: ...
    @property
    def fs(self) -> int | None: ...
    @property
    def verdict(self) -> str: ...
    @property
    def margin(self) -> float: ...
    def __repr__(self) -> str: ...

def lowpass(cutoff: float, order: int) -> Chain: ...
def highpass(cutoff: float, order: int) -> Chain: ...
def cheby1_lowpass(cutoff: float, order: int, ripple_db: float) -> Chain: ...
def cheby1_highpass(cutoff: float, order: int, ripple_db: float) -> Chain: ...
def cheby2_lowpass(cutoff: float, order: int, atten_db: float) -> Chain: ...
def cheby2_highpass(cutoff: float, order: int, atten_db: float) -> Chain: ...
def reverb(room: float, damping: float, mix: float) -> Chain: ...
def peaking(frequency: float, gain: float, q: float) -> Chain: ...
def low_shelf(cutoff: float, gain: float, q: float) -> Chain: ...
def high_shelf(cutoff: float, gain: float, q: float) -> Chain: ...
def notch(frequency: float, q: float) -> Chain: ...
def bandpass(frequency: float, q: float) -> Chain: ...
def allpass(frequency: float, q: float) -> Chain: ...
def gain(value: float) -> Chain: ...
def normalize(peak: float) -> Chain: ...
def delay(seconds: float, mix: float) -> Chain: ...
def echo(seconds: float, feedback: float, wet: float) -> Chain: ...
def fir(taps: list[float]) -> Chain: ...
def sos_forward(x: F32, coeffs: F32) -> F32: ...
def sos_backward(grad_out: F32, x: F32, coeffs: F32) -> tuple[F32, F32]: ...

# Checkpoint import (FLAMO / torchfx DDSP): state-dict of named arrays -> certified
# (n_sections, 5) [b0,b1,b2,a1,a2] rows + stability verdict/margin + embedded fs (if any).
def import_state_dict(
    tensors: dict[str, F32],
    kind: str = "auto",
    fs: int | None = None,
    svf_type: str = "general",
    biquad_type: str = "lowpass",
    eq_f_lo: float = 40.0,
    eq_f_hi: float = 16_000.0,
    eq_max_gain_db: float = 18.0,
    project_stable: bool = False,
) -> tuple[F32, str, float, int | None]: ...

# Chain (n_sections, 5) rows as raw biquad ops, certify at fs, write a standard .fxg graph.
def save_biquad_fxg(
    path: str, sections: F32, fs: int = 48_000, force: bool = False
) -> tuple[str, float]: ...

# True in the CUDA-built ("GPU") wheel, False in the default ("CPU") wheel.
__cuda__: bool

# Defined only in the CUDA-built ("GPU") wheel (guarded by ``if __cuda__`` in ``__init__``); absent
# from the default CPU wheel. Filters a flat ``len(x)/frames``-row batch through an SOS cascade on
# the GPU (bit-accurate vs the CPU path). ``coeffs`` is flat ``[b0,b1,b2,a1,a2]·n_sections``.
def sos_filter_batch_gpu(x: F32, frames: int, coeffs: F32) -> F32: ...
