"""Type stubs for the compiled `fluxion._fluxion` extension."""

from numpy import float32
from numpy.typing import NDArray

F32 = NDArray[float32]

class Chain:
    """A lazy effect chain (a DSP graph). Compose with ``|``/``+``, apply with ``process``."""

    def process(self, x: F32, fs: int) -> F32:
        """Apply the chain to a 1-D float32 array at sample rate ``fs``."""
        ...
    def __or__(self, other: Chain) -> Chain: ...
    def __add__(self, other: Chain) -> Chain: ...
    def __repr__(self) -> str: ...

def lowpass(cutoff: float, order: int) -> Chain: ...
def highpass(cutoff: float, order: int) -> Chain: ...
def cheby1_lowpass(cutoff: float, order: int, ripple_db: float) -> Chain: ...
def cheby1_highpass(cutoff: float, order: int, ripple_db: float) -> Chain: ...
def cheby2_lowpass(cutoff: float, order: int, atten_db: float) -> Chain: ...
def cheby2_highpass(cutoff: float, order: int, atten_db: float) -> Chain: ...
def reverb(room: float, damping: float, mix: float) -> Chain: ...
def peaking(frequency: float, gain: float, q: float) -> Chain: ...
def low_shelf(cutoff: float, gain: float, q: float) -> Chain: ...
def high_shelf(cutoff: float, gain: float, q: float) -> Chain: ...
def notch(frequency: float, q: float) -> Chain: ...
def bandpass(frequency: float, q: float) -> Chain: ...
def allpass(frequency: float, q: float) -> Chain: ...
def gain(value: float) -> Chain: ...
def normalize(peak: float) -> Chain: ...
def delay(seconds: float, mix: float) -> Chain: ...
def echo(seconds: float, feedback: float, wet: float) -> Chain: ...
def sos_forward(x: F32, coeffs: F32) -> F32: ...
def sos_backward(grad_out: F32, x: F32, coeffs: F32) -> tuple[F32, F32]: ...
