"""Effects — amplitude, time, modulation, dynamics, space.

Generated by scripts/gen_interfaces.py from the op registry — do not edit. Every class here is one
row of the table in crates/fluxion-core/src/op.rs, so the name, the parameters, their defaults and
their ranges are the same ones the CLI, the chain text, C and JS see.

Build a chain by composing them, then call it::

    import fluxion as fx

    wave = fx.Wave.from_file("in.wav")
    (wave | fx.filter.Highpass(80, order=4) | fx.effect.Gain(fx.db(-3))).save("out.wav")
"""

from ._fluxion import Chain

__all__ = [
    "Chorus",
    "Compand",
    "Delay",
    "Echo",
    "Fade",
    "Flanger",
    "Gain",
    "Normalize",
    "Overdrive",
    "Phaser",
    "Reverb",
    "Reverse",
    "Tremolo",
]


def _make(cls: type, name: str, *params: float) -> Chain:
    """Construct through Chain, naming the class in any error the registry raises."""
    try:
        return Chain.__new__(cls, name, *params)
    except ValueError as e:
        raise ValueError(f"fluxion.effect.{cls.__name__}: {e}") from None


class Gain(Chain):
    """Linear gain, `y = x * gain`.

    gain: default 1.0, range -inf..inf
    """

    def __new__(cls, gain: float = 1.0) -> "Gain":
        return _make(cls, "gain", gain)


class Normalize(Chain):
    """Peak normalization to a target linear `peak`.

    peak: default 1.0, range 0.0..inf
    """

    def __new__(cls, peak: float = 1.0) -> "Normalize":
        return _make(cls, "normalize", peak)


class Delay(Chain):
    """Single delayed tap crossfaded with the dry signal (`time` s, `mix`).

    time: default 0.25, range 0.0..60.0 s
    mix: default 0.5, range 0.0..1.0
    """

    def __new__(cls, time: float = 0.25, mix: float = 0.5) -> "Delay":
        return _make(cls, "delay", time, mix)


class Echo(Chain):
    """Feedback echo: `wet` repeating echoes spaced `time` s apart with `feedback`.

    time: default 0.25, range 0.0..60.0 s
    feedback: default 0.3, range 0.0..0.99
    wet: default 0.5, range 0.0..1.0
    """

    def __new__(cls, time: float = 0.25, feedback: float = 0.3, wet: float = 0.5) -> "Echo":
        return _make(cls, "echo", time, feedback, wet)


class Reverb(Chain):
    """Schroeder–Moorer reverb (`room` size, `damping`, wet/dry `mix`).

    room: default 0.5, range 0.0..1.0
    damping: default 0.3, range 0.0..1.0
    mix: default 0.3, range 0.0..1.0
    """

    def __new__(cls, room: float = 0.5, damping: float = 0.3, mix: float = 0.3) -> "Reverb":
        return _make(cls, "reverb", room, damping, mix)


class Fade(Chain):
    """Amplitude fade: `fadein` seconds ramping in, `fadeout` seconds ramping out, with a `shape`
    curve (0 = linear, 1 = quarter-sine [the SoX default], 2 = half-sine). Length-preserving.

    fadein: default 0.0, range 0.0..3600.0 s
    fadeout: default 0.0, range 0.0..3600.0 s
    shape: default 1.0, range 0.0..2.0
    """

    def __new__(cls, fadein: float = 0.0, fadeout: float = 0.0, shape: float = 1.0) -> "Fade":
        return _make(cls, "fade", fadein, fadeout, shape)


class Tremolo(Chain):
    """Tremolo: amplitude LFO at `rate` Hz dipping by `depth` (0..1). Length-preserving.

    rate: default 5.0, range 0.0..20000.0 Hz
    depth: default 0.5, range 0.0..1.0
    """

    def __new__(cls, rate: float = 5.0, depth: float = 0.5) -> "Tremolo":
        return _make(cls, "tremolo", rate, depth)


class Overdrive(Chain):
    """Overdrive: `gain` dB of drive through a `tanh` soft-clipper with a `colour` asymmetry bias.
    Nonlinear (not differentiable here).

    gain: default 20.0, range 0.0..100.0 dB
    colour: default 0.2, range 0.0..1.0
    """

    def __new__(cls, gain: float = 20.0, colour: float = 0.2) -> "Overdrive":
        return _make(cls, "overdrive", gain, colour)


class Compand(Chain):
    """Feed-forward compressor / expander (compand): one-pole peak-envelope follower (`attack`,
    `release` s) driving a soft-knee gain computer (`threshold` dBFS, `ratio`, `knee` dB, `makeup`
    dB). Stateful per-channel — realtime-playable.

    attack: default 0.01, range 0.0..10.0 s
    release: default 0.1, range 0.0..10.0 s
    threshold: default -20.0, range -120.0..0.0 dB
    ratio: default 4.0, range 1.0..100.0
    knee: default 6.0, range 0.0..48.0 dB
    makeup: default 0.0, range -48.0..48.0 dB
    """

    def __new__(cls, attack: float = 0.01, release: float = 0.1, threshold: float = -20.0, ratio: float = 4.0, knee: float = 6.0, makeup: float = 0.0) -> "Compand":
        return _make(cls, "compand", attack, release, threshold, ratio, knee, makeup)


class Reverse(Chain):
    """Per-channel time reversal (no parameters). Length-preserving, but not realtime (it needs the
    whole signal).
    """

    def __new__(cls) -> "Reverse":
        return _make(cls, "reverse")


class Chorus(Chain):
    """Chorus: an LFO-modulated fractional-delay voice (`rate` Hz, `depth` s, `delay` s) blended by
    `mix`. Feed-forward (no feedback). Length-preserving.

    rate: default 1.5, range 0.0..100.0 Hz
    depth: default 0.002, range 0.0..1.0 s
    delay: default 0.025, range 0.0..1.0 s
    mix: default 0.5, range 0.0..1.0
    """

    def __new__(cls, rate: float = 1.5, depth: float = 0.002, delay: float = 0.025, mix: float = 0.5) -> "Chorus":
        return _make(cls, "chorus", rate, depth, delay, mix)


class Flanger(Chain):
    """Flanger: a short LFO-modulated delay (`rate` Hz, `depth` s, `delay` s) with `feedback`, blended
    by `mix`. Length-preserving.

    rate: default 0.5, range 0.0..100.0 Hz
    depth: default 0.002, range 0.0..1.0 s
    delay: default 0.001, range 0.0..1.0 s
    feedback: default 0.5, range -0.95..0.95
    mix: default 0.5, range 0.0..1.0
    """

    def __new__(cls, rate: float = 0.5, depth: float = 0.002, delay: float = 0.001, feedback: float = 0.5, mix: float = 0.5) -> "Flanger":
        return _make(cls, "flanger", rate, depth, delay, feedback, mix)


class Phaser(Chain):
    """Phaser: an LFO-swept cascade of first-order all-pass stages (`rate` Hz, `depth`) with
    `feedback`, blended by `mix`. Length-preserving.

    rate: default 0.5, range 0.0..100.0 Hz
    depth: default 0.5, range 0.0..1.0
    feedback: default 0.5, range -0.95..0.95
    mix: default 0.5, range 0.0..1.0
    """

    def __new__(cls, rate: float = 0.5, depth: float = 0.5, feedback: float = 0.5, mix: float = 0.5) -> "Phaser":
        return _make(cls, "phaser", rate, depth, feedback, mix)
