"""Filters — ops that shape the spectrum.

Generated by scripts/gen_interfaces.py from the op registry — do not edit. Every class here is one
row of the table in crates/fluxion-core/src/op.rs, so the name, the parameters, their defaults and
their ranges are the same ones the CLI, the chain text, C and JS see.

Build a chain by composing them, then call it::

    import fluxion as fx

    wave = fx.Wave.from_file("in.wav")
    (wave | fx.filter.Highpass(80, order=4) | fx.effect.Gain(fx.db(-3))).save("out.wav")
"""

from ._fluxion import Chain

__all__ = [
    "Allpass",
    "Bandpass",
    "Biquad",
    "Cheby1Highpass",
    "Cheby1Lowpass",
    "Cheby2Highpass",
    "Cheby2Lowpass",
    "Fir",
    "HighShelf",
    "Highpass",
    "LowShelf",
    "Lowpass",
    "Notch",
    "Peaking",
]


def _make(cls: type, name: str, *params: float) -> Chain:
    """Construct through Chain, naming the class in any error the registry raises."""
    try:
        return Chain.__new__(cls, name, *params)
    except ValueError as e:
        raise ValueError(f"fluxion.filter.{cls.__name__}: {e}") from None


class Lowpass(Chain):
    """Butterworth low-pass filter (`cutoff` Hz, integer `order`). The `lowpass` node.

    cutoff: default 1000.0, range 0.0..inf Hz
    order: default 2.0, range 1.0..16.0
    """

    def __new__(cls, cutoff: float = 1000.0, order: float = 2.0) -> "Lowpass":
        return _make(cls, "lowpass", cutoff, order)


class Highpass(Chain):
    """Butterworth high-pass filter (`cutoff` Hz, integer `order`). The `highpass` node.

    cutoff: default 1000.0, range 0.0..inf Hz
    order: default 2.0, range 1.0..16.0
    """

    def __new__(cls, cutoff: float = 1000.0, order: float = 2.0) -> "Highpass":
        return _make(cls, "highpass", cutoff, order)


class Peaking(Chain):
    """RBJ peaking EQ: `gain` dB around `frequency` with bandwidth `q`.

    frequency: default 1000.0, range 0.0..inf Hz
    gain: default 0.0, range -inf..inf dB
    q: default 0.707, range 0.001..1000.0
    """

    def __new__(cls, frequency: float = 1000.0, gain: float = 0.0, q: float = 0.707) -> "Peaking":
        return _make(cls, "peaking", frequency, gain, q)


class LowShelf(Chain):
    """RBJ low shelf: `gain` dB below `frequency` (bandwidth `q`).

    frequency: default 1000.0, range 0.0..inf Hz
    gain: default 0.0, range -inf..inf dB
    q: default 0.707, range 0.001..1000.0
    """

    def __new__(cls, frequency: float = 1000.0, gain: float = 0.0, q: float = 0.707) -> "LowShelf":
        return _make(cls, "lowshelf", frequency, gain, q)


class HighShelf(Chain):
    """RBJ high shelf: `gain` dB above `frequency` (bandwidth `q`).

    frequency: default 1000.0, range 0.0..inf Hz
    gain: default 0.0, range -inf..inf dB
    q: default 0.707, range 0.001..1000.0
    """

    def __new__(cls, frequency: float = 1000.0, gain: float = 0.0, q: float = 0.707) -> "HighShelf":
        return _make(cls, "highshelf", frequency, gain, q)


class Notch(Chain):
    """RBJ notch at `frequency` with bandwidth `q`.

    frequency: default 1000.0, range 0.0..inf Hz
    q: default 0.707, range 0.001..1000.0
    """

    def __new__(cls, frequency: float = 1000.0, q: float = 0.707) -> "Notch":
        return _make(cls, "notch", frequency, q)


class Bandpass(Chain):
    """RBJ band-pass (0 dB peak) at `frequency` with bandwidth `q`.

    frequency: default 1000.0, range 0.0..inf Hz
    q: default 0.707, range 0.001..1000.0
    """

    def __new__(cls, frequency: float = 1000.0, q: float = 0.707) -> "Bandpass":
        return _make(cls, "bandpass", frequency, q)


class Allpass(Chain):
    """RBJ all-pass at `frequency` with bandwidth `q`.

    frequency: default 1000.0, range 0.0..inf Hz
    q: default 0.707, range 0.001..1000.0
    """

    def __new__(cls, frequency: float = 1000.0, q: float = 0.707) -> "Allpass":
        return _make(cls, "allpass", frequency, q)


class Cheby1Lowpass(Chain):
    """Chebyshev Type I low-pass (`cutoff` Hz, `order`, passband `ripple` dB).

    cutoff: default 1000.0, range 0.0..inf Hz
    order: default 4.0, range 1.0..16.0
    ripple: default 1.0, range 0.01..12.0 dB
    """

    def __new__(cls, cutoff: float = 1000.0, order: float = 4.0, ripple: float = 1.0) -> "Cheby1Lowpass":
        return _make(cls, "cheby1_lowpass", cutoff, order, ripple)


class Cheby1Highpass(Chain):
    """Chebyshev Type I high-pass (`cutoff` Hz, `order`, passband `ripple` dB).

    cutoff: default 1000.0, range 0.0..inf Hz
    order: default 4.0, range 1.0..16.0
    ripple: default 1.0, range 0.01..12.0 dB
    """

    def __new__(cls, cutoff: float = 1000.0, order: float = 4.0, ripple: float = 1.0) -> "Cheby1Highpass":
        return _make(cls, "cheby1_highpass", cutoff, order, ripple)


class Cheby2Lowpass(Chain):
    """Chebyshev Type II low-pass (`cutoff` = stopband edge Hz, `order`, stopband `atten` dB).

    cutoff: default 1000.0, range 0.0..inf Hz
    order: default 4.0, range 1.0..16.0
    atten: default 40.0, range 10.0..120.0 dB
    """

    def __new__(cls, cutoff: float = 1000.0, order: float = 4.0, atten: float = 40.0) -> "Cheby2Lowpass":
        return _make(cls, "cheby2_lowpass", cutoff, order, atten)


class Cheby2Highpass(Chain):
    """Chebyshev Type II high-pass (`cutoff` = stopband edge Hz, `order`, stopband `atten` dB).

    cutoff: default 1000.0, range 0.0..inf Hz
    order: default 4.0, range 1.0..16.0
    atten: default 40.0, range 10.0..120.0 dB
    """

    def __new__(cls, cutoff: float = 1000.0, order: float = 4.0, atten: float = 40.0) -> "Cheby2Highpass":
        return _make(cls, "cheby2_highpass", cutoff, order, atten)


class Fir(Chain):
    """Direct-form FIR filter: `y[n] = Σ_k taps[k]·x[n-k]`. Variadic — its parameters are the tap
    vector itself (one or more), the realtime/graph form of a trained or frozen FIR. The one
    parameter listed is the prototype for a single tap.

    tap: default 1.0, range -inf..inf
    """

    def __new__(cls, *taps: float) -> "Fir":
        return _make(cls, "fir", *(taps or (1.0,)))


class Biquad(Chain):
    """A raw second-order section from explicit coefficients `b0 b1 b2 a1 a2` (`a0` normalized to 1).
    Reuses the biquad/SOS machinery, so it is differentiable / freezable / realtime like the
    designed filters.

    b0: default 1.0, range -inf..inf
    b1: default 0.0, range -inf..inf
    b2: default 0.0, range -inf..inf
    a1: default 0.0, range -inf..inf
    a2: default 0.0, range -inf..inf
    """

    def __new__(cls, b0: float = 1.0, b1: float = 0.0, b2: float = 0.0, a1: float = 0.0, a2: float = 0.0) -> "Biquad":
        return _make(cls, "biquad", b0, b1, b2, a1, a2)
