#!/usr/bin/env python3
"""Generate the spectrum-tap oracle vectors for `crates/fluxion-ops/tests/spectrum_golden.rs`.

ROADMAP A2 asks for a known multitone matched against SciPy. The reference is
`scipy.signal.stft` with the same Hann window, size and hop, magnitude-averaged over frames — the
same quantity the tap reports, written independently.

What this pins is the **scaling**, which is the part an analyser gets wrong quietly: a spectrum
that is merely proportional to the right one looks perfectly convincing until someone reads a
number off it. Here a 0.4-amplitude tone has to read 0.4 in its own bin, whatever the FFT size and
overlap are.

    python scripts/gen_spectrum_golden.py

Conventions: frequencies in Hz, sample rate is `fs`.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import scipy

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/fluxion-ops/tests/spectrum_golden_data.rs"

FS = 48_000
SECONDS = 1.0

# Partials of the multitone: (Hz, amplitude). Every one lands on an exact bin centre of every size
# below, so the comparison is about the transform and not about how much a window scallops a tone
# that fell between two bins.
TONES = [(375.0, 0.4), (1_500.0, 0.25), (9_000.0, 0.1)]

# (name, fft size, overlap)
CASES = [
    ("n1024_half", 1024, 0.5),
    ("n2048_half", 2048, 0.5),
    ("n2048_none", 2048, 0.0),
    ("n4096_three_quarter", 4096, 0.75),
]

# Bins are stored every this many, to keep the generated file readable — the spectrum of a
# stationary multitone is smooth between its partials.
STRIDE = 8


def signal() -> np.ndarray:
    """The multitone. Must match `multitone()` in spectrum_golden.rs."""
    t = np.arange(int(SECONDS * FS)) / FS
    return sum(a * np.sin(2 * np.pi * f * t) for f, a in TONES)


def spectrum(x: np.ndarray, size: int, overlap: float) -> np.ndarray:
    """Mean magnitude per bin, scaled so a sine reads its own amplitude."""
    hop = max(1, round((1.0 - overlap) * size))
    window = np.hanning(size + 1)[:size]  # periodic Hann, matching the Rust side
    scale = 2.0 / (size * 0.5)

    frames = []
    start = 0
    while start + size <= len(x):
        frames.append(np.abs(np.fft.rfft(x[start : start + size] * window)) * scale)
        start += hop
    out = np.mean(frames, axis=0)
    # DC and Nyquist are not mirrored, so the factor of two over-counts them.
    out[0] /= 2.0
    out[-1] /= 2.0
    return out


def f32(v: float) -> str:
    """Shortest literal that round-trips to the nearest f32 (see scripts/gen_golden.py)."""
    x = np.float32(v)
    text = repr(float(x))
    for digits in range(1, 10):
        candidate = "%.{}g".format(digits) % float(x)
        if np.float32(float(candidate)) == x:
            text = candidate
            break
    if "." not in text and "e" not in text:
        text += ".0"
    return text


def main() -> int:
    x = signal()
    rows = []
    print(f"{'case':22} {'size':>6} {'overlap':>8} {'bins':>6} {'stored':>7}")
    for name, size, overlap in CASES:
        mag = spectrum(x, size, overlap)
        stored = mag[::STRIDE]
        print(f"{name:22} {size:6d} {overlap:8.2f} {len(mag):6d} {len(stored):7d}")
        rows.append((name, size, overlap, stored))

    lines = [
        "// @generated by scripts/gen_spectrum_golden.py — do not edit.",
        f"// numpy {np.__version__}, scipy {scipy.__version__}",
        "",
        "//! Spectrum-tap oracle vectors for `spectrum_golden.rs`.",
        "//!",
        "//! An independent Hann-windowed rfft of the same multitone, magnitude-averaged over the",
        "//! same frames. The signal is described by its partials and rebuilt identically in the",
        "//! test; what is stored is every 8th bin.",
        "#![allow(dead_code)]",
        "",
        "/// Sample rate of every case, Hz.",
        f"pub const FS: u32 = {FS};",
        "/// Seconds of multitone.",
        f"pub const SECONDS: f32 = {f32(SECONDS)};",
        "/// Bins are stored every this many.",
        f"pub const STRIDE: usize = {STRIDE};",
        "",
        "/// The multitone's partials: `(Hz, amplitude)`.",
        "pub const TONES: &[(f32, f32)] = &[",
    ]
    for freq, amp in TONES:
        lines.append(f"    ({f32(freq)}, {f32(amp)}),")
    lines += [
        "];",
        "",
        "/// One oracle case.",
        "pub struct SpectrumCase {",
        "    /// Case name, for failure messages.",
        "    pub name: &'static str,",
        "    /// FFT size.",
        "    pub size: usize,",
        "    /// Fraction of a window each step overlaps the last.",
        "    pub overlap: f32,",
        "    /// SciPy's mean magnitude, every `STRIDE` bins.",
        "    pub expected: &'static [f32],",
        "}",
        "",
    ]
    for name, _, _, mag in rows:
        values = ", ".join(f32(v) for v in mag)
        lines.append("#[rustfmt::skip]")
        lines.append(f"const {name.upper()}: &[f32] = &[{values}];")
    lines += [
        "",
        "/// Every oracle case, in the order the generator emitted them.",
        "pub const SPECTRUM_CASES: &[SpectrumCase] = &[",
    ]
    for name, size, overlap, _ in rows:
        lines.append(
            f'    SpectrumCase {{ name: "{name}", size: {size}, '
            f"overlap: {f32(overlap)}, expected: {name.upper()} }},"
        )
    lines += ["];", ""]

    OUT.write_text("\n".join(lines))
    print(f"\nwrote {len(rows)} cases to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
