#!/usr/bin/env python3
"""Generate everything that has to agree with the op registry.

The registry lives in one table in `fluxion-core/src/op.rs`. This script reads it out through
`fluxion effects --json` and writes the files that would otherwise be hand-kept copies of it:

    docs/ops.md                                    the cross-interface op table
    crates/fluxion-py/python/fluxion/filter.py     one class per filter op (+ .pyi stubs)
    crates/fluxion-py/python/fluxion/effect.py     one class per effect op (+ .pyi stubs)
    crates/fluxion-wasm/js/ops.js                  the catalog as data (+ .d.ts types)

CI runs this and then `git diff --exit-code`, so a hand edit to a generated file, or an op added
without regenerating, turns the build red. That is what makes "an op ships on every interface"
checkable rather than aspirational — see docs/interfaces.md.

Usage:
    python scripts/gen_interfaces.py            # write the generated files
    python scripts/gen_interfaces.py --check    # exit 1 if anything would change

Conventions: frequencies in Hz, sample rate is `fs`.
"""

from __future__ import annotations

import json
import re
import subprocess
import textwrap
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANNER = "<!-- generated by scripts/gen_interfaces.py — do not edit -->"

# A quickstart may not exceed this many code lines. If one does, that is a bug in the API, not in
# the quickstart (ROADMAP task I7). Counting lives here so all five interfaces are measured the
# same way; the rule itself is written down in docs/interfaces.md.
QUICKSTART_MAX_LINES = 10
COMMENT_PREFIXES = ("//", "#", "/*", "*", "--")


# One quickstart per interface, each executed in CI so it cannot rot. See docs/interfaces.md.
QUICKSTARTS = [
    ("Rust", "crates/fluxion-facade/src/lib.rs"),
    ("CLI", "crates/fluxion-cli/tests/quickstart.sh"),
    ("Python", "crates/fluxion-py/tests/quickstart.py"),
    ("C", "crates/fluxion-ffi/examples/quickstart.c"),
    ("JS", "crates/fluxion-wasm/js/quickstart.mjs"),
]
QUICKSTART_MARKERS = ("quickstart:start", "quickstart:end")


def code_lines(text: str) -> int:
    """Lines that carry code: non-blank, not a comment."""
    return sum(
        1
        for line in text.splitlines()
        if line.strip() and not line.strip().startswith(COMMENT_PREFIXES)
    )


def quickstart_body(path: Path) -> str:
    """The quickstart itself.

    Most are a whole file. The Rust one is a doctest living inside the facade's module docs, so it
    is delimited by `quickstart:start` / `quickstart:end` markers and its rustdoc `//! ` prefixes
    are stripped before counting.
    """
    lines = path.read_text().splitlines()
    start, end = QUICKSTART_MARKERS
    try:
        first = next(n for n, line in enumerate(lines) if start in line)
        last = next(n for n, line in enumerate(lines) if end in line)
    except StopIteration:
        return "\n".join(lines)
    return "\n".join(
        line.removeprefix("//!").strip()
        for line in lines[first + 1 : last]
        if "```" not in line
    )


def check_quickstarts() -> int:
    """Enforce the ten-line budget. Returns how many are over it."""
    over = 0
    print("quickstarts:")
    for label, rel in QUICKSTARTS:
        path = ROOT / rel
        if not path.exists():
            print(f"  {label:7} — not written yet ({rel})")
            continue
        count = code_lines(quickstart_body(path))
        verdict = "ok" if count <= QUICKSTART_MAX_LINES else "OVER BUDGET"
        print(f"  {label:7} {count:2}/{QUICKSTART_MAX_LINES} lines — {verdict}")
        over += count > QUICKSTART_MAX_LINES
    return over


def registry() -> dict:
    """The op catalog, straight from the binary that owns it."""
    out = subprocess.run(
        ["cargo", "run", "-q", "-p", "fluxion-cli", "--", "effects", "--json"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(out.stdout)


def plain(doc: str) -> str:
    """Rustdoc prose into prose that reads anywhere: drop intra-doc link brackets and bold."""
    doc = re.sub(r"\[(`[^`]+`)\]", r"\1", doc)  # [`OpKind::foo`] -> `OpKind::foo`
    doc = doc.replace("**", "")
    return " ".join(doc.split())


UNIT_LABEL = {"hz": " Hz", "db": " dB", "seconds": " s", "q": "", "linear": ""}


def number(value: float | None, sign: str = "") -> str:
    """Render a bound; `null` means unbounded."""
    if value is None:
        return f"{sign}∞"
    if value == int(value) and abs(value) < 1e15:
        return str(int(value))
    return str(value)


def signature(op: dict) -> str:
    """`lowpass(cutoff=1000, order=2)` — the call, with every default filled in."""
    args = ", ".join(f"{p['name']}={number(p['default'])}" for p in op["params"])
    if op["variadic"]:
        args = f"{args}, ..."
    return f"{op['name']}({args})" if args else op["name"]


def ranges(op: dict) -> str:
    """`cutoff 0..∞ Hz · order 1..16` — the bounds an error message will quote back at you."""
    return " · ".join(
        f"`{p['name']}` {number(p['min'], '-')}..{number(p['max'])}{UNIT_LABEL[p['unit']]}"
        for p in op["params"]
    )


def ops_md(reg: dict) -> str:
    """docs/ops.md — one row per op, one column per interface."""
    lines = [
        BANNER,
        "",
        "# The op catalog",
        "",
        f"{len(reg['ops'])} ops, generated from the single table in",
        "[`crates/fluxion-core/src/op.rs`](../crates/fluxion-core/src/op.rs). The rule this table",
        "exists to enforce is in [interfaces.md](interfaces.md): **an op ships on every interface,",
        "or this document says why not.**",
        "",
        "Every op is reachable from its name in the [chain text syntax](chain-syntax.md), which is",
        "how C and JS reach the whole catalog without one symbol per op. Rust and Python spell the",
        "same op as a function and a class respectively, both named from the row below.",
        "",
        "| chain text / CLI | Rust | Python | C · JS |",
        "|---|---|---|---|",
    ]
    for op in reg["ops"]:
        lines.append(
            f"| `{op['name']}` "
            f"| `prelude::{op['name']}` "
            f"| `fluxion.{op['group']}.{op['class']}` "
            f"| via chain text |"
        )

    lines += ["", "## What each op does", ""]
    for group, title in (("filter", "Filters"), ("effect", "Effects")):
        lines += [f"### {title}", ""]
        for op in (o for o in reg["ops"] if o["group"] == group):
            lines.append(f"**`{signature(op)}`** — {plain(op['doc'])}")
            if op["params"]:
                lines.append("")
                lines.append(f"> {ranges(op)}")
            lines.append("")

    lines += [
        "## Geometry stages (CLI only)",
        "",
        "These change the frame count, the sample rate or the channel layout, so they cannot be",
        "graph ops: the `|` / `+` algebra assumes every node preserves all three. They live in",
        "`fluxion_ops::transform` and run between graph passes. Bringing them into the registry is",
        "a design round of its own — see the 'Not yet' section of [interfaces.md](interfaces.md).",
        "",
        "| stage | what it does | flags |",
        "|---|---|---|",
    ]
    for stage in reg["stages"]:
        flags = ", ".join(f"`--{f['name']}` ({f['note']})" for f in stage["flags"]) or "—"
        lines.append(f"| `{stage['name']}` | {stage['summary']} | {flags} |")
    lines.append("")
    return "\n".join(lines)


# --- Python: one class per op, over the Chain base ---------------------------------------------

PY_HEADER = '''"""{title}

Generated by scripts/gen_interfaces.py from the op registry — do not edit. Every class here is one
row of the table in crates/fluxion-core/src/op.rs, so the name, the parameters, their defaults and
their ranges are the same ones the CLI, the chain text, C and JS see.

Build a chain by composing them, then call it::

    import fluxion as fx

    wave = fx.Wave.from_file("in.wav")
    (wave | fx.filter.Highpass(80, order=4) | fx.effect.Gain(fx.db(-3))).save("out.wav")
"""

from ._fluxion import Chain

__all__ = [
{exports}]


def _make(cls: type, name: str, *params: float) -> Chain:
    """Construct through Chain, naming the class in any error the registry raises."""
    try:
        return Chain.__new__(cls, name, *params)
    except ValueError as e:
        raise ValueError(f"fluxion.{module}.{{cls.__name__}}: {{e}}") from None

'''

PYI_HEADER = """# Generated by scripts/gen_interfaces.py — do not edit.
from ._fluxion import Chain

"""


def py_default(value: float) -> str:
    return repr(float(value))


def py_bound(value: float | None, sign: str = "") -> str:
    return f"{sign}inf" if value is None else py_default(value)


def docstring(op: dict) -> list[str]:
    """The doc comment from the registry, plus one line per parameter."""
    doc = plain(op["doc"])
    if '"""' in doc:
        raise SystemExit(f"op '{op['name']}' has a doc comment containing a triple quote")
    wrapped = textwrap.wrap(doc, width=95)
    lines = [f'    """{wrapped[0]}'] + [f"    {line}" for line in wrapped[1:]]
    if op["params"]:
        lines.append("")
        for p in op["params"]:
            unit = UNIT_LABEL[p["unit"]]
            rng = f"{py_bound(p['min'], '-')}..{py_bound(p['max'])}{unit}"
            lines.append(f"    {p['name']}: default {py_default(p['default'])}, range {rng}")
    lines.append('    """')
    return lines


def py_class(op: dict) -> str:
    name, cls = op["name"], op["class"]
    body = docstring(op)
    if op["variadic"]:
        # A variadic op's parameters are the vector itself, so it takes *args and falls back to the
        # registry default when called bare.
        default = py_default(op["params"][0]["default"])
        body.append("")
        body.append(f'    def __new__(cls, *{op["params"][0]["name"]}s: float) -> "{cls}":')
        body.append(
            f'        return _make(cls, "{name}", *({op["params"][0]["name"]}s or ({default},)))'
        )
    else:
        args = "".join(
            f", {p['name']}: float = {py_default(p['default'])}" for p in op["params"]
        )
        forward = "".join(f", {p['name']}" for p in op["params"])
        body.append("")
        body.append(f'    def __new__(cls{args}) -> "{cls}":')
        body.append(f'        return _make(cls, "{name}"{forward})')
    return f"\nclass {cls}(Chain):\n" + "\n".join(body) + "\n"


def py_module(reg: dict, group: str) -> str:
    ops = [o for o in reg["ops"] if o["group"] == group]
    title = {"filter": "Filters — ops that shape the spectrum.",
             "effect": "Effects — amplitude, time, modulation, dynamics, space."}[group]
    exports = "".join(f'    "{o["class"]}",\n' for o in sorted(ops, key=lambda o: o["class"]))
    header = PY_HEADER.format(title=title, exports=exports, module=group)
    return header + "\n".join(py_class(o) for o in ops)


def pyi_module(reg: dict, group: str) -> str:
    out = [PYI_HEADER]
    for op in (o for o in reg["ops"] if o["group"] == group):
        cls = op["class"]
        if op["variadic"]:
            args = f", *{op['params'][0]['name']}s: float"
        else:
            args = "".join(f", {p['name']}: float = ..." for p in op["params"])
        out.append(f"class {cls}(Chain):\n    def __new__(cls{args}) -> {cls}: ...\n")
    return "\n".join(out)


# --- JavaScript: the op catalog as data, and the types over it --------------------------------

JS_PREAMBLE = """\
// Generated by scripts/gen_interfaces.py from the op registry — do not edit.
//
// The catalog as plain data: op names, groups, parameters, defaults and ranges, identical to what
// the Rust library, the CLI, Python and C see. The wasm module deliberately does not carry this
// (it would grow the download for something most pages never read at run time), so it lives here
// where a bundler can drop it if unused.
"""


def js_ops(reg: dict) -> str:
    """js/ops.js — the catalog, as a frozen object keyed by op name."""
    lines = [JS_PREAMBLE, "", "/** @type {Readonly<Record<string, import('./ops.js').OpSpec>>} */", "export const OPS = Object.freeze({"]
    for op in reg["ops"]:
        params = ", ".join(
            "{{ name: {n}, unit: {u}, default: {d}, min: {lo}, max: {hi} }}".format(
                n=json.dumps(p["name"]),
                u=json.dumps(p["unit"]),
                d=py_default(p["default"]),
                lo="null" if p["min"] is None else py_default(p["min"]),
                hi="null" if p["max"] is None else py_default(p["max"]),
            )
            for p in op["params"]
        )
        lines.append(f"  {json.dumps(op['name'])}: {{")
        lines.append(f"    name: {json.dumps(op['name'])},")
        lines.append(f"    group: {json.dumps(op['group'])},")
        lines.append(f"    variadic: {'true' if op['variadic'] else 'false'},")
        lines.append(f"    doc: {json.dumps(plain(op['doc']))},")
        lines.append(f"    params: [{params}],")
        lines.append("  },")
    lines.append("});")
    lines.append("")
    lines.append("/** Every op name, in catalog order. */")
    lines.append("export const OP_NAMES = Object.freeze(Object.keys(OPS));")
    lines.append("")
    return "\n".join(lines)


def js_ops_types(reg: dict) -> str:
    """js/ops.d.ts — the types, so an editor can autocomplete an op name."""
    names = "\n".join(f"  | {json.dumps(op['name'])}" for op in reg["ops"])
    return f"""{JS_PREAMBLE}
/** Every op fluxion knows, as a literal union — a typo is a compile error. */
export type OpName =
{names};

/** Which section of the catalog an op belongs to. */
export type OpGroup = "filter" | "effect";

/** What a parameter is measured in. */
export type Unit = "hz" | "db" | "seconds" | "q" | "linear";

/** One parameter of an op. `min` / `max` are `null` when unbounded. */
export interface OpParam {{
  readonly name: string;
  readonly unit: Unit;
  readonly default: number;
  readonly min: number | null;
  readonly max: number | null;
}}

/** One op: what it is called, what it does, and what it takes. */
export interface OpSpec {{
  readonly name: OpName;
  readonly group: OpGroup;
  /** True when the parameters are a variable-length list rather than a fixed tuple (`fir`). */
  readonly variadic: boolean;
  readonly doc: string;
  readonly params: readonly OpParam[];
}}

export declare const OPS: Readonly<Record<OpName, OpSpec>>;
export declare const OP_NAMES: readonly OpName[];
"""


def write(path: Path, content: str, check: bool) -> bool:
    """Write `content`, or in check mode report whether it differs. True if changed."""
    current = path.read_text() if path.exists() else None
    if current == content:
        return False
    if check:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    check = "--check" in sys.argv
    reg = registry()
    py = ROOT / "crates/fluxion-py/python/fluxion"

    js = ROOT / "crates/fluxion-wasm/js"

    changed = write(ROOT / "docs/ops.md", ops_md(reg), check)
    for group in ("filter", "effect"):
        changed |= write(py / f"{group}.py", py_module(reg, group), check)
        changed |= write(py / f"{group}.pyi", pyi_module(reg, group), check)
    changed |= write(js / "ops.js", js_ops(reg), check)
    changed |= write(js / "ops.d.ts", js_ops_types(reg), check)

    if check and changed:
        print(
            "\nRun `python scripts/gen_interfaces.py` and commit the result.",
            file=sys.stderr,
        )
        return 1

    over = check_quickstarts()
    if over:
        print(
            f"\n{over} quickstart(s) over the {QUICKSTART_MAX_LINES}-line budget. That is a bug in "
            "the API, not in the quickstart — see docs/interfaces.md.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
