#!/usr/bin/env python3
"""Generate the envelope-follower oracle vectors for `crates/fluxion-ops/tests/follower_golden.rs`.

ROADMAP S2 asks for a SciPy reference on noise, and there is exactly one arrangement where SciPy
can give one: when attack and release are equal the follower is **linear**, and it is then the
one-pole `lfilter([1-a], [1, -a], level)` — nothing more. With the two times different it switches
coefficient per sample depending on which way the level is going, which is not an LTI filter and
not something `lfilter` can express; that half is checked in `follower.rs` against the closed-form
attack and release curves instead.

What this pins is the **convention**, which is the part an implementation can get wrong while
looking perfectly reasonable: that the coefficient is `exp(-1/(t·fs))` with `t` the RC time
constant, that Peak smooths `|x|`, and that RMS smooths `x²` and roots the result at the end
rather than smoothing `|x|` and calling it RMS.

    python scripts/gen_follower_golden.py

Conventions: frequencies in Hz, sample rate is `fs`.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import scipy.signal as ss

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/fluxion-ops/tests/follower_golden_data.rs"

FS = 48_000
FRAMES = 4_800

# (name, time constant in seconds, detector)
CASES = [
    ("fast_peak", 0.001, "peak"),
    ("slow_peak", 0.050, "peak"),
    ("fast_rms", 0.001, "rms"),
    ("slow_rms", 0.050, "rms"),
]

# The envelope is sampled rather than stored whole: it is smooth by construction, so every 64th
# value pins it as well as all of them and keeps the generated file readable.
STRIDE = 64


def noise(n: int) -> np.ndarray:
    """The same LCG the Rust test rebuilds. Must match `lcg()` in follower_golden.rs."""
    out = np.empty(n)
    state = np.uint32(0x1234_5678)
    for i in range(n):
        state = np.uint32(
            (np.uint64(state) * np.uint64(1_664_525) + np.uint64(1_013_904_223))
            & np.uint64(0xFFFF_FFFF)
        )
        out[i] = (int(state) >> 8) / 16_777_216.0 * 2.0 - 1.0
    return out * 0.5


def follow(x: np.ndarray, seconds: float, detector: str) -> np.ndarray:
    """A one-pole follower with attack == release, which is a plain `lfilter`."""
    a = np.exp(-1.0 / (seconds * FS))
    level = np.abs(x) if detector == "peak" else x**2
    smoothed = ss.lfilter([1.0 - a], [1.0, -a], level)
    return smoothed if detector == "peak" else np.sqrt(np.maximum(smoothed, 0.0))


def f32(v: float) -> str:
    """Shortest literal that round-trips to the nearest f32 (see scripts/gen_golden.py)."""
    x = np.float32(v)
    text = repr(float(x))
    for digits in range(1, 10):
        candidate = "%.{}g".format(digits) % float(x)
        if np.float32(float(candidate)) == x:
            text = candidate
            break
    if "." not in text and "e" not in text:
        text += ".0"
    return text


def main() -> int:
    x = noise(FRAMES)
    rows = []
    print(f"{'case':12} {'tau':>8} {'detector':>9} {'samples':>8}")
    for name, seconds, detector in CASES:
        env = follow(x, seconds, detector)[::STRIDE]
        print(f"{name:12} {seconds:8.3f} {detector:>9} {len(env):8d}")
        rows.append((name, seconds, detector, env))

    lines = [
        "// @generated by scripts/gen_follower_golden.py — do not edit.",
        f"// numpy {np.__version__}, scipy {ss.__name__.split('.')[0]} lfilter",
        "",
        "//! Envelope-follower oracle vectors for `follower_golden.rs`.",
        "//!",
        "//! SciPy's `lfilter` running the one-pole the follower reduces to when attack and release",
        "//! are equal. The noise is described by its generator and rebuilt identically in the test;",
        "//! what is stored is every 64th envelope sample.",
        "#![allow(dead_code)]",
        "",
        "/// Sample rate of every case, Hz.",
        f"pub const FS: u32 = {FS};",
        "/// Input length in frames.",
        f"pub const FRAMES: usize = {FRAMES};",
        "/// Envelope samples are stored every this many frames.",
        f"pub const STRIDE: usize = {STRIDE};",
        "",
        "/// One oracle case.",
        "pub struct FollowerCase {",
        "    /// Case name, for failure messages.",
        "    pub name: &'static str,",
        "    /// Attack and release time constant, seconds (equal, so the follower is linear).",
        "    pub seconds: f32,",
        "    /// `\"peak\"` or `\"rms\"`.",
        "    pub detector: &'static str,",
        "    /// SciPy's envelope, every `STRIDE` frames.",
        "    pub expected: &'static [f32],",
        "}",
        "",
    ]
    for name, _, _, env in rows:
        values = ", ".join(f32(v) for v in env)
        lines.append("#[rustfmt::skip]")
        lines.append(f"const {name.upper()}: &[f32] = &[{values}];")
    lines += [
        "",
        "/// Every oracle case, in the order the generator emitted them.",
        "pub const FOLLOWER_CASES: &[FollowerCase] = &[",
    ]
    for name, seconds, detector, _ in rows:
        lines.append(
            f'    FollowerCase {{ name: "{name}", seconds: {f32(seconds)}, '
            f'detector: "{detector}", expected: {name.upper()} }},'
        )
    lines += ["];", ""]

    OUT.write_text("\n".join(lines))
    print(f"\nwrote {len(rows)} cases to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
