#!/usr/bin/env python3
"""Generate everything that has to agree with the op registry.

The registry lives in one table in `fluxion-core/src/op.rs`. This script reads it out through
`fluxion effects --json` and writes the files that would otherwise be hand-kept copies of it:

    docs/ops.md                                    the cross-interface op table

CI runs this and then `git diff --exit-code`, so a hand edit to a generated file, or an op added
without regenerating, turns the build red. That is what makes "an op ships on every interface"
checkable rather than aspirational — see docs/interfaces.md.

Usage:
    python scripts/gen_interfaces.py            # write the generated files
    python scripts/gen_interfaces.py --check    # exit 1 if anything would change

Conventions: frequencies in Hz, sample rate is `fs`.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANNER = "<!-- generated by scripts/gen_interfaces.py — do not edit -->"

# A quickstart may not exceed this many code lines. If one does, that is a bug in the API, not in
# the quickstart (ROADMAP task I7). Counting lives here so all five interfaces are measured the
# same way; the rule itself is written down in docs/interfaces.md.
QUICKSTART_MAX_LINES = 10
COMMENT_PREFIXES = ("//", "#", "/*", "*", "--")


def code_lines(text: str) -> int:
    """Lines that carry code: non-blank, not a comment."""
    return sum(
        1
        for line in text.splitlines()
        if line.strip() and not line.strip().startswith(COMMENT_PREFIXES)
    )


def registry() -> dict:
    """The op catalog, straight from the binary that owns it."""
    out = subprocess.run(
        ["cargo", "run", "-q", "-p", "fluxion-cli", "--", "effects", "--json"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(out.stdout)


def plain(doc: str) -> str:
    """Rustdoc prose into prose that reads anywhere: drop intra-doc link brackets and bold."""
    doc = re.sub(r"\[(`[^`]+`)\]", r"\1", doc)  # [`OpKind::foo`] -> `OpKind::foo`
    doc = doc.replace("**", "")
    return " ".join(doc.split())


UNIT_LABEL = {"hz": " Hz", "db": " dB", "seconds": " s", "q": "", "linear": ""}


def number(value: float | None, sign: str = "") -> str:
    """Render a bound; `null` means unbounded."""
    if value is None:
        return f"{sign}∞"
    if value == int(value) and abs(value) < 1e15:
        return str(int(value))
    return str(value)


def signature(op: dict) -> str:
    """`lowpass(cutoff=1000, order=2)` — the call, with every default filled in."""
    args = ", ".join(f"{p['name']}={number(p['default'])}" for p in op["params"])
    if op["variadic"]:
        args = f"{args}, ..."
    return f"{op['name']}({args})" if args else op["name"]


def ranges(op: dict) -> str:
    """`cutoff 0..∞ Hz · order 1..16` — the bounds an error message will quote back at you."""
    return " · ".join(
        f"`{p['name']}` {number(p['min'], '-')}..{number(p['max'])}{UNIT_LABEL[p['unit']]}"
        for p in op["params"]
    )


def ops_md(reg: dict) -> str:
    """docs/ops.md — one row per op, one column per interface."""
    lines = [
        BANNER,
        "",
        "# The op catalog",
        "",
        f"{len(reg['ops'])} ops, generated from the single table in",
        "[`crates/fluxion-core/src/op.rs`](../crates/fluxion-core/src/op.rs). The rule this table",
        "exists to enforce is in [interfaces.md](interfaces.md): **an op ships on every interface,",
        "or this document says why not.**",
        "",
        "Every op is reachable from its name in the [chain text syntax](chain-syntax.md), which is",
        "how C and JS reach the whole catalog without one symbol per op. Rust and Python spell the",
        "same op as a function and a class respectively, both named from the row below.",
        "",
        "| chain text / CLI | Rust | Python | C · JS |",
        "|---|---|---|---|",
    ]
    for op in reg["ops"]:
        lines.append(
            f"| `{op['name']}` "
            f"| `prelude::{op['name']}` "
            f"| `fluxion.{op['group']}.{op['class']}` "
            f"| via chain text |"
        )

    lines += ["", "## What each op does", ""]
    for group, title in (("filter", "Filters"), ("effect", "Effects")):
        lines += [f"### {title}", ""]
        for op in (o for o in reg["ops"] if o["group"] == group):
            lines.append(f"**`{signature(op)}`** — {plain(op['doc'])}")
            if op["params"]:
                lines.append("")
                lines.append(f"> {ranges(op)}")
            lines.append("")

    lines += [
        "## Geometry stages (CLI only)",
        "",
        "These change the frame count, the sample rate or the channel layout, so they cannot be",
        "graph ops: the `|` / `+` algebra assumes every node preserves all three. They live in",
        "`fluxion_ops::transform` and run between graph passes. Bringing them into the registry is",
        "a design round of its own — see the 'Not yet' section of [interfaces.md](interfaces.md).",
        "",
        "| stage | what it does | flags |",
        "|---|---|---|",
    ]
    for stage in reg["stages"]:
        flags = ", ".join(f"`--{f['name']}` ({f['note']})" for f in stage["flags"]) or "—"
        lines.append(f"| `{stage['name']}` | {stage['summary']} | {flags} |")
    lines.append("")
    return "\n".join(lines)


def write(path: Path, content: str, check: bool) -> bool:
    """Write `content`, or in check mode report whether it differs. True if changed."""
    current = path.read_text() if path.exists() else None
    if current == content:
        return False
    if check:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    check = "--check" in sys.argv
    reg = registry()
    changed = write(ROOT / "docs/ops.md", ops_md(reg), check)

    if check and changed:
        print(
            "\nRun `python scripts/gen_interfaces.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
